version = 1

exclude_patterns = ["cast-fe/"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "gitlab.com/daystram/cast/cast-be"

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["cast-be/Dockerfile"]
